### ISSUE TITLE
Membaca data yang sudah tersimpan

### ISSUE THREAD

**Issue by cloudwalkerid** [AdityaSetyadi/form-gear#1]
![image](https://user-images.githubusercontent.com/79505272/167581798-c712d9ad-3024-47c6-b1b4-d3eb5e2b6850.png)

Tidak bisa baca data yang sudah dikirim

**Comment by ardian28** [comment]
The issue actually happened because the backend process on android/mobile failed to get the template file at the time of production. You may try again now, since the backend has been updated, then share with us the findings

Thanks for bring out the issue, truly appreciate. 🚀
